#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &
~/.config/polybar/launch.sh &
feh --bg-fill ~/effective-bspwm-pancake/wallpaper.jpg &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         2
bspc config window_gap          12
bspc config normal_border_color "#8f3f71"
bspc config active_border_color "#d3869b"
bspc config focused_border_color "#b16286"
bspc config presel-feedback_color "#b16286"

bspc config focus_follows_pointer true
bspc config pointer_follows_focus true


bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
